package demo.vacation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EmployeeVacationEntitlement implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private demo.vacation.Employee employee;
   private int entitlement;

   public EmployeeVacationEntitlement()
   {
   }

   public demo.vacation.Employee getEmployee()
   {
      return this.employee;
   }

   public void setEmployee(demo.vacation.Employee employee)
   {
      this.employee = employee;
   }

   public int getEntitlement()
   {
      return this.entitlement;
   }

   public void setEntitlement(int entitlement)
   {
      this.entitlement = entitlement;
   }

   public EmployeeVacationEntitlement(demo.vacation.Employee employee,
         int entitlement)
   {
      this.employee = employee;
      this.entitlement = entitlement;
   }

}